# Generated by Django 6.1 on 2026-08-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JustMyBiologyJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
